FROM python:3.8-slim

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends vim

COPY requirements.txt /tmp/requirements.txt
RUN pip install --trusted-host pypi.org --no-cache-dir --upgrade pip && \
    pip install --trusted-host pypi.org --no-cache-dir -r /tmp/requirements.txt

RUN apt-get autoremove -y --purge && \
    apt-get clean -y

WORKDIR /app

RUN echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('apterek', 'apterek@mail.ru', '271036yY#')" | python manage.py shell

CMD python manage.py migrate

CMD python manage.py runserver 0.0.0.0:8000
