# Generated by Django 3.2.6 on 2021-09-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210928_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='choise',
            field=models.IntegerField(choices=[(1, 'routers'), (2, 'switches')], default=1),
        ),
    ]
