# Generated by Django 3.2.6 on 2021-10-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210929_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', 'In Stock'), ('OUT_OF_STOCK', 'Out Of Stock'), ('ALL_PRODUCT', 'All products')], default='IN_STOCK', max_length=100),
        ),
    ]
