# Generated by Django 3.2.6 on 2021-10-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Spider',
                'verbose_name_plural': 'Spiders',
            },
        ),
    ]
