# Generated by Django 3.2.6 on 2021-10-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_spider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spider',
            name='price',
            field=models.CharField(max_length=15),
        ),
    ]
