# Generated by Django 3.2.6 on 2021-10-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_spider_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='spider',
            name='image_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
