# Generated by Django 3.2.6 on 2021-10-21 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_purchase_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_byn',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='shop.product'),
        ),
    ]
