# Generated by Django 3.2.6 on 2021-10-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20211021_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cost_byn',
            new_name='price_byn',
        ),
    ]
