# Generated by Django 3.2.6 on 2021-08-25 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
