# Generated by Django 3.2.6 on 2021-09-13 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
