# Generated by Django 3.2.6 on 2021-09-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_remove_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=25)),
                ('product_cost', models.FloatField(max_length=10)),
                ('description', models.TextField(max_length=200)),
                ('vendor_code', models.IntegerField(max_length=8)),
                ('serial_number', models.CharField(max_length=16)),
            ],
        ),
    ]
